import { useState } from 'react';
import Navbar from '../components/common/Navbar';
import Sidebar from '../components/common/Sidebar';
import Card from '../components/common/Card';
import Button from '../components/common/Button';
import { useApp } from '../context/AppContext';
import { moodAPI, quizAPI, journalAPI } from '../services/api';
import { FileDown, Download, FileText } from 'lucide-react';

export default function ExportData() {
  const { user } = useApp();
  const [loading, setLoading] = useState(false);
  const [exportType, setExportType] = useState('mood');

  const generateReport = async () => {
    setLoading(true);
    try {
      let data, filename, title;
      
      switch (exportType) {
        case 'mood':
          const moodRes = await moodAPI.getAll(user._id);
          data = moodRes.data;
          filename = `mindbridge_mood_report_${new Date().toISOString().split('T')[0]}.txt`;
          title = 'Mood Tracking Report';
          break;
        case 'quiz':
          const quizRes = await quizAPI.getAll(user._id);
          data = quizRes.data;
          filename = `mindbridge_quiz_report_${new Date().toISOString().split('T')[0]}.txt`;
          title = 'Self-Assessment Quiz Report';
          break;
        case 'journal':
          const journalRes = await journalAPI.getAll(user._id);
          data = journalRes.data;
          filename = `mindbridge_journal_report_${new Date().toISOString().split('T')[0]}.txt`;
          title = 'Journal Entries Report';
          break;
        case 'full':
          const [moodData, quizData, journalData] = await Promise.all([
            moodAPI.getAll(user._id),
            quizAPI.getAll(user._id),
            journalAPI.getAll(user._id)
          ]);
          data = { moods: moodData.data, quizzes: quizData.data, journals: journalData.data };
          filename = `mindbridge_full_report_${new Date().toISOString().split('T')[0]}.txt`;
          title = 'Complete MindBridge Report';
          break;
        default:
          return;
      }

      let content = `========================================\n${title}\n========================================\n\n`;
      content += `Generated: ${new Date().toLocaleString()}\n`;
      content += `User: ${user.name}\n`;
      content += `Email: ${user.email}\n`;
      if (user.role === 'student' && user.department) {
        content += `Academic Profile: ${user.program} - ${user.department} (Year ${user.yearOfStudy})\n`;
        content += `Roll No: ${user.universityRollNo}\n`;
      }
      content += `========================================\n\n`;

      if (exportType === 'mood' || exportType === 'full') {
        content += `MOOD ENTRIES (${data.moods?.length || data.length || 0} total)\n`;
        content += `----------------------------------------\n`;
        const moods = data.moods || data;
        moods.forEach(entry => {
          content += `${new Date(entry.date).toLocaleDateString()}: Mood ${entry.mood}/5`;
          if (entry.note) content += ` - ${entry.note}`;
          content += '\n';
        });
        content += '\n';
      }

      if (exportType === 'quiz' || exportType === 'full') {
        content += `SELF-ASSESSMENT QUIZZES (${data.quizzes?.length || 0} total)\n`;
        content += `----------------------------------------\n`;
        data.quizzes?.forEach(quiz => {
          content += `${new Date(quiz.date).toLocaleDateString()}: ${quiz.quizType}\n`;
          content += `  Score: ${quiz.score} | Severity: ${quiz.severity}\n\n`;
        });
        content += '\n';
      }

      if (exportType === 'journal' || exportType === 'full') {
        content += `JOURNAL ENTRIES (${data.journals?.length || 0} total)\n`;
        content += `----------------------------------------\n`;
        data.journals?.forEach(entry => {
          content += `${new Date(entry.date).toLocaleDateString()}\n`;
          content += `${entry.content}\n\n`;
        });
      }

      content += `\n========================================\n`;
      content += `This report was generated by MindBridge\n`;
      content += `Your mental health data is confidential\n`;
      content += `========================================\n`;

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export error:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background-light dark:bg-background-dark transition-colors duration-300">
      <Navbar />
      <div className="flex">
        <Sidebar />
        <main className="flex-1 p-4 lg:p-8 lg:ml-64">
          <div className="max-w-2xl mx-auto">
            <div className="mb-8">
              <h1 className="text-3xl font-bold text-gray-800 dark:text-white mb-2">Export Your Data</h1>
              <p className="text-gray-500 dark:text-gray-400">
                Download your mental health data for personal records
              </p>
            </div>

            <Card>
              <div className="flex items-center mb-6">
                <FileText className="w-8 h-8 text-primary dark:text-primary mr-3" />
                <div>
                  <h3 className="font-semibold text-gray-800 dark:text-white">Privacy Notice</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Your data is stored securely and export is for your personal use only
                  </p>
                </div>
              </div>

              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Select what to export
                </label>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { id: 'mood', label: 'Mood Entries', icon: '📊' },
                    { id: 'quiz', label: 'Quiz Results', icon: '📋' },
                    { id: 'journal', label: 'Journal Entries', icon: '📝' },
                    { id: 'full', label: 'Full Report', icon: '📦' }
                  ].map(opt => (
                    <button
                      key={opt.id}
                      onClick={() => setExportType(opt.id)}
                      className={`p-4 rounded-xl text-left transition-all ${
                        exportType === opt.id
                          ? 'bg-primary dark:bg-primary text-white'
                          : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
                      }`}
                    >
                      <span className="text-2xl mr-2">{opt.icon}</span>
                      {opt.label}
                    </button>
                  ))}
                </div>
              </div>

              <Button onClick={generateReport} disabled={loading} icon={Download} className="w-full">
                {loading ? 'Generating...' : 'Download Report'}
              </Button>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}


